Release/17.0.0
EtherCorp/u_medical_connection pull request #18
Opened 2017-10-12 23:38 UTC by MonodetH

Implements ETL for gathering information of medical centers

* Accepts a patient information json through an API
* Queue the request for processing
* Transform the request's data to a standardized schema
* Persists the information sending the data to Unicorns' API

2017-10-26 21:41 UTC, dochoaj requested changes
Les dejé comentarios!

2017-10-26 21:41 UTC, dochoaj commented on centers-api/Gemfile
> +gem 'grape'
Fijar las versiones de las gemas

2017-10-26 21:41 UTC, dochoaj commented on centers-api/app/api/v1/base.rb
> +      puts '************************'
Hay maneras de crear logs sin usar puts.

2017-10-26 21:41 UTC, dochoaj commented on centers-api/app/controllers/jsons_controller.rb
> +class JsonsController < ApplicationController
No usemos controllers, usemos Grape para manejar parámetros JSON

2017-10-26 21:41 UTC, dochoaj commented on centers-api/app/models/json.rb
> +class Json
Le cambiaría el nombre a la clase.

2017-10-26 21:41 UTC, dochoaj commented on centers-api/app/requests/request/consult.rb
> +      dir = @@url + @entity + "/" + id.to_s + "/" + "movements"
Cuando los strings no necesitan interpolación, se usa comilla simple.

2017-10-26 21:41 UTC, dochoaj commented on centers-api/app/requests/request/speciality.rb
> +
Muchos espacios innecesarios

2017-10-26 21:41 UTC, dochoaj commented on centers-api/app/workers/dispatcher_worker.rb
> +    puts 'TODO: Is saved data?'
Puts ToDO?

2017-10-26 21:41 UTC, dochoaj commented on centers-api/bin/setup
> -  # puts "\n== Copying sample files =="
Por que es esto???

2017-10-26 21:41 UTC, dochoaj commented on centers-api/bin/setup
> -  # unless File.exist?('config/database.yml')
Y esto?

2017-10-26 21:41 UTC, dochoaj commented on centers-api/config/mongoid.yml
> +development:
Esto debería ir gitignoreado, tal cual les comenté en el otro repo.

2017-10-28 08:31 UTC, MonodetH commented
@dochoaj Se arregló todo lo que comentó

2017-11-09 02:29 UTC, closed without merging