Feature/endpoints api
EtherCorp/u_medical_connection pull request #20
Opened 2017-10-25 16:37 UTC by JavieraSaezLeon

- Faker genera datos para professionals and consults
- Endpoint de API para consultas profesionales y movimientos agregados
- Drivers para profesionales y consultas

- Flujo probado hasta el uso de los drivers

2017-10-25 19:56 UTC, gzunigal requested changes
Hay que cambiar la rama de destino a develop

2017-10-25 20:02 UTC, Sacranister commented
Cambio a rama destino develop

2017-10-27 02:44 UTC, gzunigal approved these changes

2017-10-27 02:54 UTC, gzunigal requested changes
Bien, pero hay que resolver un conflicto y dejar de usar puts para loggear

2017-10-27 02:54 UTC, MonodetH commented on centers-api/Gemfile
> +=======
Hay que resolver el conflicto

2017-10-27 02:54 UTC, MonodetH commented on centers-api/app/api/v1/base.rb
> +      puts '************************'
No loggear con puts. Preferir [logger](https://ruby-doc.org/stdlib-2.4.0/libdoc/logger/rdoc/Logger.html)

2017-10-27 03:30 UTC, gzunigal approved these changes

2017-11-06 00:17 UTC, closed without merging